/* Generated By:JavaCC: Do not edit this line. mas2jConstants.java */
package jason.mas2j.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface mas2jConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int MAS = 7;
  /** RegularExpression Id. */
  int AGS = 8;
  /** RegularExpression Id. */
  int ENV = 9;
  /** RegularExpression Id. */
  int CONTROL = 10;
  /** RegularExpression Id. */
  int AT = 11;
  /** RegularExpression Id. */
  int INFRA = 12;
  /** RegularExpression Id. */
  int CLASSPATH = 13;
  /** RegularExpression Id. */
  int SOURCEPATH = 14;
  /** RegularExpression Id. */
  int ASOEE = 15;
  /** RegularExpression Id. */
  int ASOEEV = 16;
  /** RegularExpression Id. */
  int ASOIB = 17;
  /** RegularExpression Id. */
  int ASOIBV = 18;
  /** RegularExpression Id. */
  int ASONRC = 19;
  /** RegularExpression Id. */
  int ASOV = 20;
  /** RegularExpression Id. */
  int DIRECTIVE = 21;
  /** RegularExpression Id. */
  int ASOSYNC = 22;
  /** RegularExpression Id. */
  int ASOBOOL = 23;
  /** RegularExpression Id. */
  int ASAGCLASS = 24;
  /** RegularExpression Id. */
  int ASAGARCHCLASS = 25;
  /** RegularExpression Id. */
  int BBCLASS = 26;
  /** RegularExpression Id. */
  int NUMBER = 27;
  /** RegularExpression Id. */
  int STRING = 28;
  /** RegularExpression Id. */
  int ASID = 29;
  /** RegularExpression Id. */
  int ID = 30;
  /** RegularExpression Id. */
  int PATH = 31;
  /** RegularExpression Id. */
  int DRIVER = 32;
  /** RegularExpression Id. */
  int LETTER = 33;
  /** RegularExpression Id. */
  int LC_LETTER = 34;
  /** RegularExpression Id. */
  int UP_LETTER = 35;
  /** RegularExpression Id. */
  int DIGIT = 36;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "\"MAS\"",
    "\"agents\"",
    "\"environment\"",
    "\"executionControl\"",
    "\"at\"",
    "\"infrastructure\"",
    "\"classpath\"",
    "\"aslSourcePath\"",
    "\"events\"",
    "<ASOEEV>",
    "\"intBels\"",
    "<ASOIBV>",
    "\"nrcbp\"",
    "\"verbose\"",
    "\"directives\"",
    "\"synchronised\"",
    "<ASOBOOL>",
    "\"agentClass\"",
    "\"agentArchClass\"",
    "\"beliefBaseClass\"",
    "<NUMBER>",
    "<STRING>",
    "<ASID>",
    "<ID>",
    "<PATH>",
    "<DRIVER>",
    "<LETTER>",
    "<LC_LETTER>",
    "<UP_LETTER>",
    "<DIGIT>",
    "\"{\"",
    "\"}\"",
    "\":\"",
    "\"#\"",
    "\";\"",
    "\".\"",
    "\"(\"",
    "\",\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"=\"",
  };

}
