package jcmsim.events;

import java.util.Date;
import java.util.Optional;

import cartago.*;
import cartago.events.ArtifactObsEvent;
import jcmsim.EvCtxActivity;
import jcmsim.EvCtxEvent;
import jcmsim.activities.ActWspObsStatePerceptDispatch;

public class EvWspObsStateDispatch extends EvCtxEvent {

    private ArtifactObsEvent ev;
    private AgentId observer;
        
    public EvWspObsStateDispatch(ArtifactObsEvent ev, AgentId observer) { 
        this.ev = ev;
        this.observer = observer;
    }
    
    public AgentId getAgentId() {
        return observer;
    }
    
    public ArtifactObsEvent getArtObsEvent() {
        return ev;
    }

    public String toString() {
        return "[event: wsp obs state dispatch | ev-id: " + ev.getId() + " | " + ev.getClass().getName() +" |  generated by " + ev.getArtifactId().getName() + " to be dispatched to " + observer.getAgentName() +" ]";
        
    }
    
    public Optional<EvCtxActivity> getActivityToBegin() {
        return Optional.of(new ActWspObsStatePerceptDispatch(this));
    }
    
}
