package jcmsim.events;

import java.util.Date;
import java.util.Optional;

import cartago.*;
import cartago.events.ArtifactObsEvent;
import jcmsim.ECActivity;
import jcmsim.ECEvent;
import jcmsim.activities.ActWspObsStatePerceptDispatch;

public class EvWspObsStateDispatch extends ECEvent {

    private ArtifactObsEvent ev;
    private AgentId observer;
        
    public EvWspObsStateDispatch(ArtifactObsEvent ev, AgentId observer) { 
        this.ev = ev;
        this.observer = observer;
    }
    
    public AgentId getAgentId() {
        return observer;
    }
    
    public ArtifactObsEvent getArtObsEvent() {
        return ev;
    }

    public String toString() {
        return "[event: wsp obs state dispatch | ev-id: " + ev.getId() + " | " + ev.getClass().getName() +" |  generated by " + ev.getArtifactId().getName() + " to be dispatched to " + observer.getAgentName() +" ]";
        
    }
    
    public ECActivity[] getActivitiesToBegin() {
    	return new ECActivity[] { new ActWspObsStatePerceptDispatch(this) };
    }
    
}
